# Generated by Django 5.2.8 on 2025-11-27 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('conflict', 'Armed Conflict'), ('flood', 'Flooding'), ('drought', 'Drought/Food Shortage'), ('disease', 'Disease Outbreak'), ('evacuation', 'Evacuation Order'), ('safety', 'Safety Warning'), ('resource', 'Resource Distribution'), ('meeting', 'Emergency Meeting'), ('other', 'Other Emergency')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical - Immediate Action'), ('severe', 'Severe - Act Soon'), ('moderate', 'Moderate - Be Aware'), ('info', 'Informational')], max_length=20)),
                ('target_regions', models.JSONField(default=list)),
                ('target_counties', models.JSONField(default=list)),
                ('target_states', models.JSONField(default=list)),
                ('broadcast_all', models.BooleanField(default=False)),
                ('issuing_organization', models.CharField(blank=True, max_length=255)),
                ('send_push', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=True)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('recipients_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('read_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('report_notifications', models.BooleanField(default=True)),
                ('meeting_notifications', models.BooleanField(default=True)),
                ('forum_notifications', models.BooleanField(default=True)),
                ('message_notifications', models.BooleanField(default=True)),
                ('emergency_notifications', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('report_status', 'Report Status Update'), ('report_comment', 'Report Comment'), ('meeting_invite', 'Meeting Invitation'), ('meeting_reminder', 'Meeting Reminder'), ('forum_reply', 'Forum Reply'), ('forum_mention', 'Forum Mention'), ('forum_like', 'Forum Like'), ('message', 'Direct Message'), ('emergency_alert', 'Emergency Alert'), ('verification', 'Verification Update'), ('resource_added', 'New Resource Available'), ('system', 'System Notification')], max_length=30)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('report_id', models.IntegerField(blank=True, null=True)),
                ('forum_post_id', models.IntegerField(blank=True, null=True)),
                ('meeting_id', models.IntegerField(blank=True, null=True)),
                ('message_id', models.IntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'read'], name='notificatio_recipie_6e3964_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx')],
            },
        ),
    ]
