# Generated by Django 5.2.8 on 2025-11-27 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['-featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='resource',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('legal', 'Legal Guides'), ('mental_health', 'Mental Health'), ('education', 'Education'), ('employment', 'Employment & Jobs'), ('peacebuilding', 'Peacebuilding'), ('health', 'Health & Wellness'), ('agriculture', 'Agriculture & Livelihoods'), ('womens_rights', "Women's Rights"), ('child_protection', 'Child Protection'), ('conflict_resolution', 'Conflict Resolution'), ('cultural', 'Cultural Heritage'), ('emergency', 'Emergency Resources')], default='legal', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='duration',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('audio', 'Audio'), ('video', 'Video'), ('link', 'External Link'), ('text', 'Text Guide')], default='pdf', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('dik', 'Dinka'), ('juba', 'Juba Arabic'), ('nuer', 'Nuer'), ('shiluk', 'Shiluk'), ('bari', 'Bari')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['-created_at'], name='resources_r_created_83a7af_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category'], name='resources_r_categor_8e2710_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type'], name='resources_r_resourc_1a6f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['verified'], name='resources_r_verifie_1eabb9_idx'),
        ),
        migrations.AddField(
            model_name='resourcebookmark',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='resourcebookmark',
            unique_together={('user', 'resource')},
        ),
    ]
