# Generated by Django 5.2.8 on 2025-11-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('conflict', 'Conflict / Dispute'), ('infrastructure', 'Infrastructure'), ('health', 'Health / Sanitation'), ('security', 'Security Concern'), ('livelihoods', 'Livelihoods / Employment'), ('education', 'Education / School Issues'), ('environment', 'Environment / Water Access'), ('gender', 'Gender-Based Violence'), ('resources', 'Resource Access / Aid'), ('alerts', 'Emergency / Alerts'), ('other', 'Other')], max_length=32)),
                ('location', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('photo', models.URLField(blank=True)),
                ('trusted', models.BooleanField(default=False)),
            ],
        ),
    ]
